apiVersion: v1
kind: Service
metadata:
  labels:
    app: sri-backend
  name: sri-backend
spec:
  ports:
    - name: "http"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sri-backend
  type: ClusterIP
